FROM node:boron

RUN useradd --user-group --create-home --shell /bin/false app && npm install --global nodemon

ENV HOME=/home/app

COPY package.json $HOME/dbproject/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/dbproject
RUN npm install

USER root
COPY . $HOME/dbproject
RUN chown -R app:app $HOME/*
USER app
